### ISSUE TITLE
Implement 7TV

### ISSUE THREAD

**Issue by doceazedo** [doceazedo/emotettv#15]
Implement 7TV emotes. [Docs](https://7tv.io/docs). Handle overlay/zero-width emotes. Handle personal emotes.

Later, also parse badges (#16).

Should we handle other stuff?
- Custom name colors
- Custom profile pictures

**Comment by WilliamTraoreee** [comment]
Hi! I love your package and it help me a lot on my project.
Do you have an ETA on this feature?

Thanks a lot for your work!

**Comment by doceazedo** [comment]
@WilliamTraoreee Hey, thanks for the interest! I'm currently refactoring the lib and that includes adding 7TV support. I plan to release it this week :)

**Comment by WilliamTraoreee** [comment]
So quick! It's amazing! :)

**Comment by doceazedo** [comment]
@WilliamTraoreee 7TV support is now available on 1.0.0, please notice that the API has changed a bit. Thank you for your patience :)
